# Generated by Django 3.2.7 on 2021-09-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='date_devolution',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
